highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: http://nreith.github.com/vitae
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://nreith.github.com/vitae
author: Nicholas Reith

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Nicholas Reith's Resume
name: Nicholas Reith
email: nreith@gmail.com
email_full: mailto:nreith@gmail.com
website: nicholasreith.com
website_full: https://www.nicholasreith.com
github: nreith
linkedin: nreith
indeed: Nicholas-Reith/a90523aac9609797
#twitter: twitter
tel: +1 (646) 821 1880
tel_full: tel:+1 (646) 821 1880
google_maps: 'https://www.google.com/maps/place/Hyde+Park,+Austin,+TX/@30.3067907,-97.7332168,15z/data=!3m1!4b1!4m2!3m1!1s0x8644ca710dd9e5b5:0x526d78512aa5b73c'
#address: Austin, Texas
postcode: 78705
city: Austin, Texas
country: United States
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
